---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: step-certificates
  repo: https://smallstep.github.io/helm-charts
  version: 1.26.2
  releaseName: step-ca
  namespace: cert-manager
  valuesFile: values.yaml