service:
  type: LoadBalancer
  port: 8443
  targetPort: 8443

bootstrap:
  enabled: true
  
ca:
  name: "skylab CA"
  address: ":8443"
  dns: "step-ca-step-certificates.cert-manager.svc.cluster.local"
  
  provisioner:
    name: "admin"
    
  persistence:
    enabled: true
    size: 1Gi
    storageClass: local-path
