---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- rbac.yaml

helmCharts:
- name: headlamp
  repo: https://kubernetes-sigs.github.io/headlamp/
  version: 0.31.1
  valuesFile: values.yaml
  releaseName: headlamp
  namespace: headlamp

