---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- step-cluster-issuer.yaml

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.13.3
  releaseName: cert-manager
  namespace: cert-manager
  valuesFile: cert-manager-values.yaml

- name: step-issuer
  repo: https://smallstep.github.io/helm-charts
  version: 1.9.8
  releaseName: step-issuer
  namespace: cert-manager
  valuesFile: step-issuer-values.yaml
