---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/namespace.yaml

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.13.3
  releaseName: cert-manager
  namespace: cert-manager
  valuesInline:
    installCRDs: true
    global:
      leaderElection:
        namespace: cert-manager
