apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/smallstep/step-issuer/config/crd?ref=master
helmCharts:
- name: cert-manager
  namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: cert-manager-values.yaml
  version: v1.13.3
- name: step-issuer
  namespace: cert-manager
  releaseName: step-issuer
  repo: https://smallstep.github.io/helm-charts
  valuesFile: step-issuer-values.yaml
  version: 1.9.8
- name: trust-manager
  namespace: cert-manager
  releaseName: trust-manager
  repo: https://charts.jetstack.io
  version: 0.19.0
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: cert-manager
    environment: dev
