---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki

resources:
  - manifests/namespace.yaml

helmCharts:
  - name: grafana/loki
    repo: https://grafana.github.io/helm-charts
    version: 6.30.1
    releaseName: loki
    namespace: loki
    valuesFile: helm-chart/values.yaml

