---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ceph

resources:
  - namespace.yaml
  - storage-classes.yaml

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: v1.12.8
    releaseName: rook-ceph
    namespace: ceph-system
    valuesFile: values-operator.yaml
  - name: rook-ceph-cluster
    repo: https://charts.rook.io/release
    version: v1.12.8
    releaseName: rook-ceph-cluster
    namespace: ceph
    valuesFile: values-cluster.yaml
    includeCRDs: true
