---
apiVersion: v2
name: external-secrets-config
description: External Secrets Operator configuration
version: 1.0.0

dependencies:
- name: external-secrets
  version: "0.9.11"
  repository: "https://charts.external-secrets.io"