apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- includeCRDs: true
  name: external-secrets
  namespace: external-secrets
  releaseName: es
  repo: https://charts.external-secrets.io
  valuesFile: values.yaml
  version: 0.9.11
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: external-secrets
    environment: dev
