---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-secrets
  version: 0.9.11
  repo: https://charts.external-secrets.io
  releaseName: es
  valuesFile: values.yaml
  namespace: external-secrets
  includeCRDs: true

commonLabels:
  app.kubernetes.io/name: external-secrets
  app.kubernetes.io/component: secrets-management
  environment: dev