apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/SkylarHoughtonGithub/skylab-argo-workloads
      revision: HEAD
      directories:
      - path: infra/*
  # When you add more clusters, add more generators
  # - git:
  #     repoURL: https://github.com/SkylarHoughtonGithub/skylab-argo-workloads
  #     revision: HEAD
  #     directories:
  #     - path: infra/*
  #   template:
  #     metadata:
  #       name: 'staging-{{path.basename}}'
  #     destination:
  #       server: https://staging-cluster.example.com
  template:
    metadata:
      name: 'in-cluster-{{path.basename}}'
      labels:
        cluster: in-cluster
        environment: dev
        component: infra
        service: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/SkylarHoughtonGithub/skylab-argo-workloads
        targetRevision: HEAD
        path: '{{path}}/dev'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true