---
# issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-issuer
spec:
  acme:
    server: https://step-ca.step-ca.svc.cluster.local:9000/acme/acme/directory
    email: shoutsky@skylab.local
    privateKeySecretRef:
      name: step-ca-acme-account-key
    skipTLSVerify: true    
    solvers:
    - http01:
        ingress:
          class: traefik
          podTemplate:
            metadata:
              annotations:
                cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
