apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mikrotik-credentials-all
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mikrotik-secret-all
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: mikrotik-credentials  # Gets all key-value pairs from the secret