apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: grafana/admin
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None