admin:
  existingSecret: grafana-admin-secret
  userKey: username
  passwordKey: password

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/issuer: step-ca-cluster-issuer
    cert-manager.io/issuer-kind: StepClusterIssuer  
    cert-manager.io/issuer-group: certmanager.step.sm
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - grafana.skylarhoughtongithub.local
  tls:
  - secretName: grafana-tls
    hosts:
    - grafana.skylarhoughtongithub.local 

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.loki.svc.cluster.local
      isDefault: true
      editable: true

persistence:
  enabled: true
  size: 5Gi
