apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mikrotik-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mikrotik-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      conversionStrategy: Default	
      decodingStrategy: None
      key: mikrotik-credentials
      metadataPolicy: None