---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system

resources:
- github.com/awslabs/crossplane-on-eks/compositions?ref=main
- github.com/awslabs/crossplane-on-eks/compositions/upbound-aws-provider?ref=main