apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    provider: aws
    service: eks-access
  name: eks-access-entries-composition
spec:
  compositeTypeRef:
    apiVersion: infrastructure.skylab.com/v1alpha1
    kind: XEKSAccessEntries
  mode: Resources
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  resources:
    # Admin Access Entry (Optional)
    - base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: AccessEntry
        spec:
          forProvider:
            principalArn: ""
            type: STANDARD
            tags:
              ManagedBy: crossplane
              AccessType: admin
              PrincipalType: ""
            clusterNameRef:
              name: ""
          providerConfigRef:
            name: default
      name: admin-access-entry
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-admin-access-entry'
                type: Format
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterNameRef.name
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.awsAccountId
              - fromFieldPath: spec.adminPrincipal.type
              - fromFieldPath: spec.adminPrincipal.name
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:%s/%s"
          toFieldPath: spec.forProvider.principalArn
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.adminPrincipal.type
          toFieldPath: spec.forProvider.tags.PrincipalType
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
      readinessChecks:
        - matchCondition:
            status: 'True'
            type: Ready
          type: MatchCondition

    # Admin Access Policy Association (Optional)
    - base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: AccessPolicyAssociation
        spec:
          forProvider:
            accessScope:
              - type: cluster
            policyArn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
            principalArn: ""
            clusterNameRef:
              name: ""
          providerConfigRef:
            name: default
      name: admin-policy-association
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-admin-policy-association'
                type: Format
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterNameRef.name
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.awsAccountId
              - fromFieldPath: spec.adminPrincipal.type
              - fromFieldPath: spec.adminPrincipal.name
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:%s/%s"
          toFieldPath: spec.forProvider.principalArn
          policy:
            fromFieldPath: Optional
      readinessChecks:
        - matchCondition:
            status: 'True'
            type: Ready
          type: MatchCondition

    # ReadOnly Access Entry (Optional)
    - base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: AccessEntry
        spec:
          forProvider:
            principalArn: ""
            type: STANDARD
            tags:
              ManagedBy: crossplane
              AccessType: readonly
              PrincipalType: ""
            clusterNameRef:
              name: ""
          providerConfigRef:
            name: default
      name: readonly-access-entry
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-readonly-access-entry'
                type: Format
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterNameRef.name
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.awsAccountId
              - fromFieldPath: spec.readonlyPrincipal.type
              - fromFieldPath: spec.readonlyPrincipal.name
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:%s/%s"
          toFieldPath: spec.forProvider.principalArn
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.readonlyPrincipal.type
          toFieldPath: spec.forProvider.tags.PrincipalType
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
      readinessChecks:
        - matchCondition:
            status: 'True'
            type: Ready
          type: MatchCondition

    # ReadOnly Access Policy Association (Optional)
    - base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: AccessPolicyAssociation
        spec:
          forProvider:
            accessScope:
              - type: cluster
            policyArn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSAdminViewPolicy
            principalArn: ""
            clusterNameRef:
              name: ""
          providerConfigRef:
            name: default
      name: readonly-policy-association
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-readonly-policy-association'
                type: Format
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterNameRef.name
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.awsAccountId
              - fromFieldPath: spec.readonlyPrincipal.type
              - fromFieldPath: spec.readonlyPrincipal.name
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:%s/%s"
          toFieldPath: spec.forProvider.principalArn
          policy:
            fromFieldPath: Optional
      readinessChecks:
        - matchCondition:
            status: 'True'
            type: Ready
          type: MatchCondition

  writeConnectionSecretsToNamespace: crossplane-system