apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    provider: aws
    service: eks-access
  name: eks-access-entries-composition
spec:
  compositeTypeRef:
    apiVersion: infrastructure.skylab.com/v1alpha1
    kind: XEKSAccessEntries
  mode: Resources
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  resources:
    # Admin Access Entry 1
    - base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: AccessEntry
        spec:
          forProvider:
            principalArn: ""
            type: STANDARD
            kubernetesGroups:
              - system:masters
            tags:
              ManagedBy: crossplane
              AccessType: admin
              PrincipalType: ""
            clusterNameRef:
              name: ""
          providerConfigRef:
            name: default
      name: admin-access-entry-1
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-admin-1'
                type: Format
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterNameRef.name
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.awsAccountId
              - fromFieldPath: spec.adminPrincipals[0].type
              - fromFieldPath: spec.adminPrincipals[0].name
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:%s/%s"
          toFieldPath: spec.forProvider.principalArn
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.adminPrincipals[0].type
          toFieldPath: spec.forProvider.tags.PrincipalType
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.adminPrincipals[0].kubernetesGroups
          toFieldPath: spec.forProvider.kubernetesGroups
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.adminPrincipals[0].accessPolicies
          toFieldPath: spec.forProvider.accessPolicy
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
      readinessChecks:	
        - matchCondition:	
            status: 'True'	
            type: Ready	
          type: MatchCondition

    # Admin Access Entry 2
    - base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: AccessEntry
        spec:
          forProvider:
            principalArn: ""
            type: STANDARD
            kubernetesGroups:
              - system:masters
            tags:
              ManagedBy: crossplane
              AccessType: admin
              PrincipalType: ""
            clusterNameRef:
              name: ""
          providerConfigRef:
            name: default
      name: admin-access-entry-2
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-admin-2'
                type: Format
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterNameRef.name
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.awsAccountId
              - fromFieldPath: spec.adminPrincipals[1].type
              - fromFieldPath: spec.adminPrincipals[1].name
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:%s/%s"
          toFieldPath: spec.forProvider.principalArn
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.adminPrincipals[1].type
          toFieldPath: spec.forProvider.tags.PrincipalType
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.adminPrincipals[1].kubernetesGroups
          toFieldPath: spec.forProvider.kubernetesGroups
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.adminPrincipals[1].accessPolicies
          toFieldPath: spec.forProvider.accessPolicy
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
      readinessChecks:	
        - matchCondition:	
            status: 'True'	
            type: Ready	
          type: MatchCondition

    # Developer Access Entry 1
    - base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: AccessEntry
        spec:
          forProvider:
            principalArn: ""
            type: STANDARD
            kubernetesGroups:
              - system:authenticated
            tags:
              ManagedBy: crossplane
              AccessType: developer
              PrincipalType: ""
            clusterNameRef:
              name: ""
          providerConfigRef:
            name: default
      name: developer-access-entry-1
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-dev-1'
                type: Format
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterNameRef.name
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.awsAccountId
              - fromFieldPath: spec.developerPrincipals[0].type
              - fromFieldPath: spec.developerPrincipals[0].name
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:%s/%s"
          toFieldPath: spec.forProvider.principalArn
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.developerPrincipals[0].type
          toFieldPath: spec.forProvider.tags.PrincipalType
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.developerPrincipals[0].kubernetesGroups
          toFieldPath: spec.forProvider.kubernetesGroups
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.developerPrincipals[0].accessPolicies
          toFieldPath: spec.forProvider.accessPolicy
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
      readinessChecks:	
        - matchCondition:	
            status: 'True'	
            type: Ready	
          type: MatchCondition

    # Developer Access Entry 2
    - base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: AccessEntry
        spec:
          forProvider:
            principalArn: ""
            type: STANDARD
            kubernetesGroups:
              - system:authenticated
            tags:
              ManagedBy: crossplane
              AccessType: developer
              PrincipalType: ""
            clusterNameRef:
              name: ""
          providerConfigRef:
            name: default
      name: developer-access-entry-2
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-dev-2'
                type: Format
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterNameRef.name
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.awsAccountId
              - fromFieldPath: spec.developerPrincipals[1].type
              - fromFieldPath: spec.developerPrincipals[1].name
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:%s/%s"
          toFieldPath: spec.forProvider.principalArn
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.developerPrincipals[1].type
          toFieldPath: spec.forProvider.tags.PrincipalType
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.developerPrincipals[1].kubernetesGroups
          toFieldPath: spec.forProvider.kubernetesGroups
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.developerPrincipals[1].accessPolicies
          toFieldPath: spec.forProvider.accessPolicy
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
      readinessChecks:	
        - matchCondition:	
            status: 'True'	
            type: Ready	
          type: MatchCondition

    # ReadOnly Access Entry 1
    - base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: AccessEntry
        spec:
          forProvider:
            principalArn: ""
            type: STANDARD
            kubernetesGroups:
              - system:authenticated
            tags:
              ManagedBy: crossplane
              AccessType: readonly
              PrincipalType: ""
            clusterNameRef:
              name: ""
          providerConfigRef:
            name: default
      name: readonly-access-entry-1
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-readonly-1'
                type: Format
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterNameRef.name
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.awsAccountId
              - fromFieldPath: spec.readonlyPrincipals[0].type
              - fromFieldPath: spec.readonlyPrincipals[0].name
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:%s/%s"
          toFieldPath: spec.forProvider.principalArn
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.readonlyPrincipals[0].type
          toFieldPath: spec.forProvider.tags.PrincipalType
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.readonlyPrincipals[0].kubernetesGroups
          toFieldPath: spec.forProvider.kubernetesGroups
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.readonlyPrincipals[0].accessPolicies
          toFieldPath: spec.forProvider.accessPolicy
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
      readinessChecks:	
        - matchCondition:	
            status: 'True'	
            type: Ready	
          type: MatchCondition

    # ReadOnly Access Entry 2
    - base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: AccessEntry
        spec:
          forProvider:
            principalArn: ""
            type: STANDARD
            kubernetesGroups:
              - system:authenticated
            tags:
              ManagedBy: crossplane
              AccessType: readonly
              PrincipalType: ""
            clusterNameRef:
              name: ""
          providerConfigRef:
            name: default
      name: readonly-access-entry-2
      patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: metadata.name
          transforms:
            - string:
                fmt: '%s-readonly-2'
                type: Format
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterNameRef.name
          type: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.awsAccountId
              - fromFieldPath: spec.readonlyPrincipals[1].type
              - fromFieldPath: spec.readonlyPrincipals[1].name
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:%s/%s"
          toFieldPath: spec.forProvider.principalArn
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.readonlyPrincipals[1].type
          toFieldPath: spec.forProvider.tags.PrincipalType
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.readonlyPrincipals[1].kubernetesGroups
          toFieldPath: spec.forProvider.kubernetesGroups
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
        - fromFieldPath: spec.readonlyPrincipals[1].accessPolicies
          toFieldPath: spec.forProvider.accessPolicy
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Optional
      readinessChecks:	
        - matchCondition:	
            status: 'True'	
            type: Ready	
          type: MatchCondition

  writeConnectionSecretsToNamespace: crossplane-system