---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- xrd-xnetwork.yaml
- xrd-xclusterrbac.yaml
- xrd-xekscluster.yaml
- xrd-xeksaccessentries.yaml
- composition-xnetwork.yaml
- composition-xclusterrbac.yaml
- composition-xekscluster.yaml
- composition-xeksaccessentries.yaml