apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeksaccessentries.infrastructure.skylab.com
spec:
  group: infrastructure.skylab.com
  names:
    kind: XEKSAccessEntries
    plural: xeksaccessentries
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              clusterName:
                type: string
                description: "Name of the EKS cluster to grant access to"
              region:
                type: string
                description: "AWS region"
                default: "us-east-2"
              awsAccountId:
                type: string
                description: "AWS Account ID for constructing IAM ARNs"
                pattern: "^[0-9]{12}$"
                default: "635314249418"
              
              # Optional admin principal with AmazonEKSClusterAdminPolicy
              adminPrincipal:
                type: object
                description: "IAM principal to grant admin access (optional)"
                properties:
                  name:
                    type: string
                    description: "Name of IAM user or role"
                  type:
                    type: string
                    enum: ["user", "role"]
                    default: "role"
                    description: "Type of IAM principal"
                required:
                  - name
              
              # Optional readonly principal with AmazonEKSAdminViewPolicy
              readonlyPrincipal:
                type: object
                description: "IAM principal to grant readonly access (optional)"
                properties:
                  name:
                    type: string
                    description: "Name of IAM user or role"
                  type:
                    type: string
                    enum: ["user", "role"]
                    default: "role"
                    description: "Type of IAM principal"
                required:
                  - name
            required:
              - clusterName
          status:
            type: object
            properties:
              adminEntry:
                type: object
                description: "Status of admin access entry"
                properties:
                  principalArn:
                    type: string
                  status:
                    type: string
                  accessEntryArn:
                    type: string
                  policyArn:
                    type: string
                    default: "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"
              readonlyEntry:
                type: object
                description: "Status of readonly access entry"
                properties:
                  principalArn:
                    type: string
                  status:
                    type: string
                  accessEntryArn:
                    type: string
                  policyArn:
                    type: string
                    default: "arn:aws:eks::aws:cluster-access-policy/AmazonEKSAdminViewPolicy"
  claimNames:
    kind: EKSAccessEntries
    plural: eksaccessentries