apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-users
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: minio-users-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: minio/users/loki