---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root-credentials
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  
  target:
    name: minio-root-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        root-user: "{{ .rootUser }}"
        root-password: "{{ .rootPassword }}"
  
  data:
    - secretKey: rootUser
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: minio/admin
        property: username
        metadataPolicy: None
    - secretKey: rootPassword
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: minio/admin
        property: password
        metadataPolicy: None