---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-users
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: minio-user-secrets
    creationPolicy: Owner
  data:
  - remoteRef:
    secretKey: accesskey
      key: minio/users/loki
      property: accesskey
  - remoteRef:
    secretKey: secretkey
      key: minio/users/loki
      property: secretkey