---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-users
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: minio-user-secrets
    creationPolicy: Owner
  data:
  - secretKey: accesskey
    remoteRef:
      key: minio/users/loki
      property: accesskey
      metadataPolicy: None
      conversionStrategy: Default	
      decodingStrategy: None
  - secretKey: secretkey
    remoteRef:
      key: minio/users/loki
      property: secretkey
      metadataPolicy: None
      conversionStrategy: Default	
      decodingStrategy: None