---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - namespace.yaml
  - es_minio_admin.yaml

helmCharts:
  - name: minio
    repo: https://charts.bitnami.com/bitnami
    version: 17.0.6
    releaseName: minio
    namespace: minio
    valuesFile: values.yaml