auth:
  existingSecret: minio-root-credentials

mode: standalone

defaultBuckets: "loki-chunks,loki-ruler,loki-admin,tempo-traces,backup-storage"

persistence:
  enabled: true
  storageClass: "local-path"
  accessModes:
    - ReadWriteOnce
  size: 100Gi

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: minio.skylarhoughtongithub.local
  annotations:
      cert-manager.io/issuer: step-ca-cluster-issuer
      cert-manager.io/issuer-kind: StepClusterIssuer  
      cert-manager.io/issuer-group: certmanager.step.sm
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
  tls: true
  
console:
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: minio-console.skylarhoughtongithub.local
    annotations:
      cert-manager.io/issuer: step-ca-cluster-issuer
      cert-manager.io/issuer-kind: StepClusterIssuer  
      cert-manager.io/issuer-group: certmanager.step.sm
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    tls: true

resources:
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector:
  node-type: worker

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

podSecurityContext:
  enabled: true
  fsGroup: 1001
  fsGroupChangePolicy: "OnRootMismatch"

extraEnvVars:
  - name: MINIO_COMPRESS
    value: "true"
  - name: MINIO_COMPRESS_EXTENSIONS
    value: ".log,.txt,.json"
  - name: MINIO_COMPRESS_MIME_TYPES
    value: "text/*,application/json,application/xml"

metrics:
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: false
networkPolicy:
  enabled: false
podDisruptionBudget:
  enabled: false

livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

startupProbe:
  enabled: true
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 60
  successThreshold: 1

provisioning:
  enabled: true
  usersExistingSecrets:
    - minio-users-secret

extraConfig: ""

podAnnotations: {}

podLabels: {}

tolerations: []

affinity: {}

volumePermissions:
  enabled: true