# #TODO: Dont apply to repo with access keys, use sops with aws kms
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: aws-credentials
#   namespace: external-secrets-system
# type: Opaque
# stringData:
#   access-key-id: "ACCESS_KEY"
#   secret-access-key: "SECRET_KEY"