# kube-vip cloud provider for LoadBalancer services
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevip
  namespace: kube-system
data:
  range-global: 192.168.50.50-192.168.50.60  # Adjust range for your network