---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-token-refresh
  namespace: external-secrets
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-token-refresher
          restartPolicy: OnFailure
          containers:
          - name: ecr-refresh
            image: amazon/aws-cli:latest
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            - name: ECR_REGISTRY
              value: "635314249418.dkr.ecr.us-east-2.amazonaws.com"
            - name: AWS_DEFAULT_REGION
              value: "us-east-2"
            command:
            - /bin/bash
            - -c
            - |
              curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
              chmod +x kubectl && mv kubectl /usr/local/bin/
              
              TOKEN=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
              
              for ns in $(kubectl get namespaces -o name | cut -d/ -f2 | grep -v '^kube-'); do
                kubectl create secret docker-registry ecr-registry-secret \
                  --docker-server=$ECR_REGISTRY \
                  --docker-username=AWS \
                  --docker-password="$TOKEN" \
                  --namespace=$ns \
                  --dry-run=client -o yaml | kubectl apply -f -
                echo "Updated: $ns"
              done