---
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-step-ca

resources:
  - manifests/namespace.yaml
  - manifests/issuer.yaml

helmCharts:
  - name: step-certificates
    repo: https://smallstep.github.io/helm-charts
    version: 1.25.0
    releaseName: step-ca
    namespace: cert-step-ca
    valuesFile: helm-chart/values.yaml
