---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ceph-cluster

resources:
  - manifests/namespace.yaml

helmCharts:
  - name: rook-ceph-cluster
    repo: https://charts.rook.io/release
    version: v1.12.8
    releaseName: rook-ceph-cluster
    namespace: ceph-cluster
    valuesFile: values.yaml
    includeCRDs: true
