loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  querier:
    max_concurrent: 4
    query_timeout: 5m
  
  query_frontend:
    max_outstanding_per_tenant: 100

  limits_config:
    query_timeout: 5m
    max_query_parallelism: 16
    max_concurrent_queries: 20
    max_cache_freshness_per_query: 10m
    retention_period: 744h

  storage_config:
    chunk_store_config:
      chunk_cache_config:
        embedded_cache:
          enabled: true
          max_size_mb: 100
    index_queries_cache_config:
      embedded_cache:
        enabled: true
        max_size_mb: 100

  schemaConfig:
    configs:
    - from: "2024-04-01"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      access_key_id: ${ACCESS_KEY_ID}
      secret_access_key: ${SECRET_ACCESS_KEY}
      endpoint: https://minio.skylarhoughtongithub.local
      s3ForcePathStyle: true
      insecure: false
  compactor:
    working_directory: /tmp/loki/compactor
    shared_store: s3
    compaction_interval: 10m

extraEnvFrom:
  - secretRef:
      name: loki-bucket-creds

global:
  dnsService: kube-dns

gateway:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: loki.skylarhoughtongithub.local
        paths:
          - path: /
            pathType: Prefix
    annotations:
      cert-manager.io/issuer: step-ca-cluster-issuer
      cert-manager.io/issuer-kind: StepClusterIssuer  
      cert-manager.io/issuer-group: certmanager.step.sm
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    tls:
      - secretName: loki-tls
        hosts:
          - loki.skylarhoughtongithub.local

read:
  replicas: 1

write:
  replicas: 1

backend:
  replicas: 1