loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  # Limits configuration (top level)
  limits_config:
    query_timeout: 5m
    max_query_parallelism: 16
    max_concurrent_tail_requests: 20
    max_cache_freshness_per_query: 10m
    retention_period: 744h  # 31 days, adjust as needed

  # Query frontend configuration
  frontend:
    max_outstanding_per_tenant: 100
    compress_responses: true

  # Querier configuration  
  querier:
    max_concurrent: 4

  # Storage configuration
  storage_config:
    boltdb_shipper:
      active_index_directory: /tmp/loki/boltdb-shipper-active
      cache_location: /tmp/loki/boltdb-shipper-cache
    index_queries_cache_config:
      embedded_cache:
        enabled: true
        max_size_mb: 100

  schemaConfig:
    configs:
    - from: "2024-04-01"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: http://minio.skylarhoughtongithub.local
      s3ForcePathStyle: true
      insecure: true
      region: us-east-1



  # Compactor configuration
  compactor:
    working_directory: /tmp/loki/compactor
    compaction_interval: 10m

extraEnvFrom:
  - secretRef:
      name: loki-bucket-creds

global:
  dnsService: kube-dns
  extraEnv:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: loki-bucket-creds
        key: ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: loki-bucket-creds
        key: SECRET_ACCESS_KEY

gateway:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: loki.skylarhoughtongithub.local
        paths:
          - path: /
            pathType: Prefix
    annotations:
      cert-manager.io/issuer: step-ca-cluster-issuer
      cert-manager.io/issuer-kind: StepClusterIssuer  
      cert-manager.io/issuer-group: certmanager.step.sm
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    tls:
      - secretName: loki-tls
        hosts:
          - loki.skylarhoughtongithub.local

# Increase resources for better performance
read:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  extraEnvFrom:
  - secretRef:
      name: loki-bucket-creds

write:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  extraEnvFrom:
  - secretRef:
      name: loki-bucket-creds

backend:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  extraEnvFrom:
  - secretRef:
      name: loki-bucket-creds

# Configure caching for better performance
chunksCache:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

resultsCache:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi