---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets-system

resources:
- manifests/cluster-secret-store.yaml

# Deploy External Secrets Operator via Helm
helmCharts:
- name: external-secrets
  version: 0.9.11
  repo: https://charts.external-secrets.io
  valuesFile: helm-chart/values.yaml
  namespace: external-secrets-system
  includeCRDs: true

# Add common labels
commonLabels:
  app.kubernetes.io/name: external-secrets
  app.kubernetes.io/component: secrets-management
  environment: dev