---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crossplane-aws-credentials
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: crossplane-aws-credentials
    creationPolicy: Owner
  data:
  - secretKey: credentials
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      key: crossplane/aws-credentials
      metadataPolicy: None
      property: credentials