---
image:
  repository: rook/ceph
  tag: v1.12.8

# Resource limits for operator
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Node selector for operator (optional)
nodeSelector:
  node-type: worker

# Tolerations for control plane nodes
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

# Enable host networking (recommended for performance)
hostNetwork: false

# CSI configuration
csi:
  enableRbdDriver: true
  enableCephfsDriver: true
  enableGrpcMetrics: true
  
  # CSI images
  csiRBDProvisionerResource: |
    - name: csi-provisioner
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    - name: csi-resizer
      resource:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m

# Admission controller settings
admissionController:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule