apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-step-cluster-issuer
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: step-config-extractor
      containers:
      - name: deployer
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Extract all values
          CA_JSON=$(kubectl get configmap -n cert-manager step-ca-step-certificates-config -o jsonpath='{.data.ca\.json}')
          PROVISIONER_NAME=$(echo "$CA_JSON" | jq -r '.authority.provisioners[0].name')
          PROVISIONER_KID=$(echo "$CA_JSON" | jq -r '.authority.provisioners[0].key.kid')
          URL=$(echo "$CA_JSON" | jq -r '("https://" + .dnsNames[0] + .address)')
          CA_BUNDLE=$(kubectl get configmap -n cert-manager step-ca-step-certificates-certs -o jsonpath='{.data.root_ca\.crt}' | base64 -w 0)
          
          # Deploy the StepClusterIssuer
          cat <<EOF | kubectl apply -f -
          apiVersion: certmanager.step.sm/v1beta1
          kind: StepClusterIssuer
          metadata:
            name: step-ca-cluster-issuer
            annotations:
              argocd.argoproj.io/sync-options: Prune=false
          spec:
            url: ${URL}
            caBundle: ${CA_BUNDLE}
            provisioner:
              name: ${PROVISIONER_NAME}
              kid: ${PROVISIONER_KID}
              passwordRef:
                name: step-ca-step-certificates-provisioner-password
                namespace: cert-manager
                key: password
          EOF
      restartPolicy: OnFailure