apiVersion: batch/v1
kind: Job
metadata:
  name: extract-step-ca-config
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: step-config-extractor
      containers:
      - name: extractor
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Extract values
          CA_JSON=$(kubectl get configmap -n cert-manager step-ca-step-certificates-config -o jsonpath='{.data.ca\.json}')
          PROVISIONER_NAME=$(echo "$CA_JSON" | jq -r '.authority.provisioners[0].name')
          PROVISIONER_KID=$(echo "$CA_JSON" | jq -r '.authority.provisioners[0].key.kid')
          URL=$(echo "$CA_JSON" | jq -r '("https://" + .dnsNames[0] + .address)')
          CA_BUNDLE=$(kubectl get configmap -n cert-manager step-ca-step-certificates-certs -o jsonpath='{.data.root_ca\.crt}' | base64 -w 0)
          
          # Create ConfigMap with extracted values
          kubectl create configmap step-ca-extracted-config \
            --from-literal=provisioner-name="$PROVISIONER_NAME" \
            --from-literal=provisioner-kid="$PROVISIONER_KID" \
            --from-literal=url="$URL" \
            --from-literal=ca-bundle="$CA_BUNDLE" \
            --dry-run=client -o yaml | kubectl apply -f -
      restartPolicy: OnFailure