apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- job_step_ca_config.yaml
- sa_step_config_extractor.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: step-issuer
    environment: dev
