---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- step-cluster-issuer.yaml

helmCharts:
- name: step-issuer
  repo: https://smallstep.github.io/helm-charts
  version: 1.9.8
  releaseName: step-issuer
  namespace: step-issuer
  valuesFile: values.yaml
