---
apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: step-ca-cluster-issuer
spec:
  url: https://step-ca-step-certificates.cert-manager.svc.cluster.local:8443
  
  # Get with: kubectl get configmap -n cert-manager step-ca-step-certificates-certs -o jsonpath='{.data.root_ca\.crt}' | base64 -w 0
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJvakNDQVVtZ0F3SUJBZ0lRZWhqZ0lUbGszVUFKQlJBQjZNR1hBakFLQmdncWhrak9QUVFEQWpBd01SSXcKRUFZRFZRUUtFd2x6YTNsc1lXSWdRMEV4R2pBWUJnTlZCQU1URVhOcmVXeGhZaUJEUVNCU2IyOTBJRU5CTUI0WApEVEkxTURZeU9URTRNVFl4T0ZvWERUTTFNRFl5TnpFNE1UWXhPRm93TURFU01CQUdBMVVFQ2hNSmMydDViR0ZpCklFTkJNUm93R0FZRFZRUURFeEZ6YTNsc1lXSWdRMEVnVW05dmRDQkRRVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQk5ZeXpOelBJN0J0a0VsRTE3eHAyVE9icGtZT1pRZVZidG5hcFZqMUhmVHNBWjlLbmNjcgp0dlFwNXJ1TTFUVzBjME5JTjRzeXZzL2tyTUVka211aGdaMmpSVEJETUE0R0ExVWREd0VCL3dRRUF3SUJCakFTCkJnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQk1CMEdBMVVkRGdRV0JCUlpBZENHRERvT0FnQzBlWG1zT2Y5eFB3NmMKL2pBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCTi82UDEvWkV2RkVZU0VsYitmM0hYbFZSSzl0cWZYcHM3bURqawoyRnJIaVFJZ2ZIVXcyTURXbkdtUDlPVU81RUdNNVNhb2ZHQmpLOGhOb1RmRVp1dVVDTXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

  provisioner:
    name: admin
    kid: 37156UB75Y3KEWFn7FIzIU-nri-_5S8eoma4xMG5O9E
    passwordRef:
      name: step-ca-step-certificates-provisioner-password
      namespace: cert-manager
      key: password