---
apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: step-ca-cluster-issuer
spec:
  url: https://step-ca-step-certificates.step-ca.svc.skylarhoughtongithub.local:8443
  
  # Get with: kubectl get configmap -n step-ca step-ca-step-certificates-certs -o jsonpath='{.data.root_ca\.crt}' | base64 -w 0
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwRENDQVVtZ0F3SUJBZ0lRT3ZvVXE0Rjl3eU8xN3ZYU096aEVXVEFLQmdncWhrak9QUVFEQWpBd01SSXcKRUFZRFZRUUtFd2x6YTNsc1lXSWdRMEV4R2pBWUJnTlZCQU1URVhOcmVXeGhZaUJEUVNCU2IyOTBJRU5CTUI0WApEVEkxTURZeU5qSXhNVGd4TjFvWERUTTFNRFl5TkRJeE1UZ3hOMW93TURFU01CQUdBMVVFQ2hNSmMydDViR0ZpCklFTkJNUm93R0FZRFZRUURFeEZ6YTNsc1lXSWdRMEVnVW05dmRDQkRRVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkJqblVSS1lJckVNc1hheWJqcDhHcTJnT0RrNmE1SC90TVJvNWhYMFVtSnR6T0F6RlU4YgpIU29MUDF5UHQzcE5UeHZxdHdjV0UrbHdIRmRMSk1tSnJxU2pSVEJETUE0R0ExVWREd0VCL3dRRUF3SUJCakFTCkJnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQk1CMEdBMVVkRGdRV0JCVHJ6TkxTa1IwVlBVYm1TUnUvdjQrZUVBQVQKVnpBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTZZV0RpL1hrT0hFRXhVL2VDMGpoeHJRbjJHakd2MEZnVDVJTQpvY2MxM0dZQ0lRRDVzL0pkVGoxellnc05ieExlb0tQOU1vbmJOcGhMZmkxZTZMT3A5S09SV3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  
  provisioner:
    name: admin
    kid: kwSC2tZnAEwyKACiaDwPQUi4MnmFP_F9XwHbQ9WLSFk
    passwordRef:
      name: step-ca-step-certificates-provisioner-password
      namespace: step-ca
      key: password