---
apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: step-ca-cluster-issuer
spec:
  url: https://step-ca-step-certificates.step-ca.svc.skylarhoughtongithub.local:8443
  
  # Get with: kubectl get configmap -n cert-manager step-ca-step-certificates-certs -o jsonpath='{.data.root_ca\.crt}' | base64 -w 0
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJvekNDQVVtZ0F3SUJBZ0lRUU9hMUIwbzZpZlJ1aTdieHRKT3loREFLQmdncWhrak9QUVFEQWpBd01SSXcKRUFZRFZRUUtFd2x6YTNsc1lXSWdRMEV4R2pBWUJnTlZCQU1URVhOcmVXeGhZaUJEUVNCU2IyOTBJRU5CTUI0WApEVEkxTURZeU9EQXpNVFV5TjFvWERUTTFNRFl5TmpBek1UVXlOMW93TURFU01CQUdBMVVFQ2hNSmMydDViR0ZpCklFTkJNUm93R0FZRFZRUURFeEZ6YTNsc1lXSWdRMEVnVW05dmRDQkRRVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQk5pRFNwcks0S3lHYlUybGdPbUgzL3VmUG5BUVhpV00zRmlNcVc1R3owZlVqZXhZdFVWZgpEbFIrY3VPemVoVWtHTmloQUNuK0xqK292ODA3QlZ5eXA1NmpSVEJETUE0R0ExVWREd0VCL3dRRUF3SUJCakFTCkJnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQk1CMEdBMVVkRGdRV0JCVEdNY1FyeXpGQjZ5SkFGRjBVanMvaTU4NEUKVURBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlCL3l1ZnVHVjl1U2RWMzAwY05GM2xSYlRzS1NpM0pQQ05LYVJFLwpWVS84Y0FJaEFQSFhwbFgrU0JpN3ZvWnp6Wnk2Tk9FWkZ2YzZZWFQzcnVNdjZoZzdxL0pZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  
  provisioner:
    name: admin
    kid: ZGOUKPbzG0yr1Km2Plkvg0Rlw_jAK0lcsQkOUUTuKtE
    passwordRef:
      name: step-ca-step-certificates-provisioner-password
      namespace: step-ca
      key: password