---
apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: step-ca-cluster-issuer
spec:
  url: https://step-ca-step-certificates.cert-manager.svc.cluster.local:8443
  
  # Get with: kubectl get configmap -n cert-manager step-ca-step-certificates-certs -o jsonpath='{.data.root_ca\.crt}' | base64 -w 0
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwRENDQVVtZ0F3SUJBZ0lRWTBJQVhLWkU4VW1xeVp5b2pRUVlYekFLQmdncWhrak9QUVFEQWpBd01SSXcKRUFZRFZRUUtFd2x6YTNsc1lXSWdRMEV4R2pBWUJnTlZCQU1URVhOcmVXeGhZaUJEUVNCU2IyOTBJRU5CTUI0WApEVEkxTURZeU9URTRNRFkwTlZvWERUTTFNRFl5TnpFNE1EWTBOVm93TURFU01CQUdBMVVFQ2hNSmMydDViR0ZpCklFTkJNUm93R0FZRFZRUURFeEZ6YTNsc1lXSWdRMEVnVW05dmRDQkRRVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkk4WHlESnhRZi9kNEVvU3V4aGRzR0pORnJnclJqUlJhSWZtcjVXUklqdmFGbVBrTTNVSQpSWTJiSTRVdGJwaTYvM2lBeGd2NUJyK1RRblM0S0JGbTh0Q2pSVEJETUE0R0ExVWREd0VCL3dRRUF3SUJCakFTCkJnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQk1CMEdBMVVkRGdRV0JCU1VNbjFXTjl2aDZUNkgrcXY4SzNEU284NEkKcGpBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXk3cElzaWZFeElMTUtJSThOaXBtSTVMVUhJOUd6eURVWkdFMwpVdExOTTFjQ0lRRCt1SGNud0xRSHBERG1oS01rY0dvaHBOSVg2blBkTmlNRGY3M2tSaWhJN1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

  provisioner:
    name: admin
    kid: -5_MI2tExh9hJ0oaHo7wHq9frHzVWfsniy9FjmNX9dk
    passwordRef:
      name: step-ca-step-certificates-provisioner-password
      namespace: cert-manager
      key: password