# test-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
  namespace: default
spec:
  secretName: test-tls
  issuerRef:
    name: step-ca-cluster-issuer
    kind: StepClusterIssuer
    group: certmanager.step.sm
  dnsNames:
  - test.skylarhoughtongithub.local
  duration: 24h0m0s
  renewBefore: 8h0m0s